// <auto-generated />
using System;
using EinkaufslistenApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EinkaufslistenApp.Migrations
{
    [DbContext(typeof(EinkaufslistenDbContext))]
    [Migration("20250223232112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EinkaufslistenApp.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Benutzer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benutzername = "Alice",
                            Passwort = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Benutzername = "Bob",
                            Passwort = "5678"
                        });
                });

            modelBuilder.Entity("EinkaufslistenApp.Models.EinkaufsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gekauft")
                        .HasColumnType("bit");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("EinkaufsItems");
                });

            modelBuilder.Entity("EinkaufslistenApp.Models.EinkaufsItem", b =>
                {
                    b.HasOne("EinkaufslistenApp.Models.Benutzer", "Benutzer")
                        .WithMany("EinkaufsItems")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("EinkaufslistenApp.Models.Benutzer", b =>
                {
                    b.Navigation("EinkaufsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
